<a href="https://grml.github.com"><img style="position: absolute; top: 0; right: 0; border: 0;" src="/img/forkme.png" alt="Fork me on GitHub"></a>

<div class="container">
      <div class="menu">
            <a class="plain" href="/"><img style="border: 0" alt="grml.org" src="/img/logo.png" class="logo" /></a>
            <h3>About</h3>
              <p>
                <a class="plain" href="/features/">Features</a><br/>
                <a class="plain" href="/team/">Team</a><br/>
                <a class="plain" href="/screenshots/">Screenshots</a><br/>
                <a class="plain" href="/sponsors/">Sponsors</a><br/>
              </p>
            <h3>News</h3>
              <p>
                <a class="plain" href="https://blog.grml.org/">Blog</a> &nbsp;
                <a href="https://twitter.com/grmlproject"><img src="/img/twitter.png" alt="Follow grmlproject on Twitter" class="absmiddle" /></a>
                <br/>

                <a class="plain" href="/changelogs/">Release Notes</a><br/>
                <a class="plain" href="/press/">Press</a><br/>
              </p>
            <h3>Getting Grml</h3>
              <p>
                <a class="plain" href="/download/">Download</a><br/>
                <a class="plain" href="/files/">Packages &amp; Files</a><br/>
              </p>
            <h3>Documentation</h3>
              <p>
                <a class="plain" href="/docs/">Documentation</a><br/>
                <a class="plain" href="/faq/"><abbr title="Frequently Asked Questions">FAQ</abbr></a><br/>
                <a class="plain" href="https://wiki.grml.org/">Wiki</a><br/>
                <a class="plain" href="/zsh/"><abbr title="The Z shell - the geek's shell">Zsh</abbr></a><br/>
              </p>
            <h3>Development</h3>
              <p>
                <a class="plain" href="/bugs/">Reporting Bugs</a><br/>
                <a class="plain" href="/bugs/known/">Known Bugs</a><br/>
                <a class="plain" href="/beta/">Beta Versions</a><br/>
                <a class="plain" href="https://grml.github.com/">Contribute</a><br/>
              </p>
            <h3>Get in touch</h3>
              <p>
                <a class="plain" href="/contact/">Contact</a><br/>
              </p>

            <div class="copyright">&copy; Copyright 2003-2020 Grml Live Linux</div>
            <p>&nbsp;</p>

      </div>
