
<div class="container">
      <div class="menu">
            <a class="plain" href="/"><img style="border: 0" alt="grml.org" src="/img/logo.png" class="logo" /></a>
            <h3>About</h3>
              <p>
                <a class="plain" href="/features/">Features</a><br/>
                <a class="plain" href="/team/">Team</a><br/>
                <a class="plain" href="/screenshots/">Screenshots</a><br/>
                <a class="plain" href="/sponsors/">Sponsors</a><br/>
              </p>
            <h3>News</h3>
              <p>
                <a class="plain" href="http://blog.grml.org/">Blog</a> &nbsp;
                <a href="https://www.twitter.com/grmlproject"><img src="/img/twitter.png" alt="Follow grmlproject on Twitter" class="absmiddle" /></a>
                <a href="https://identi.ca/grml"><img src="/img/identica.png" alt="Follow grml on identi.ca" class="absmiddle" /></a>
                <br/>

                <a class="plain" href="/changelogs/">Release Notes</a><br/>
                <a class="plain" href="/press/">Press</a><br/>
              </p>
            <h3>Getting grml</h3>
              <p>
                <a class="plain" href="/download/">Download</a><br/>
                <a class="plain" href="/order/">Order a CD</a><br/>
                <a class="plain" href="/files/">Packages &amp; Files</a><br/>
              </p>
            <h3>Documentation</h3>
              <p>
                <a class="plain" href="/docs/">Documentation</a><br/>
                <a class="plain" href="/faq/"><abbr title="Frequently Asked Questions">FAQ</abbr></a><br/>
                <a class="plain" href="http://wiki.grml.org/">Wiki</a><br/>
                <a class="plain" href="/zsh/"><abbr title="The Z shell - the geek's shell">Zsh</abbr></a><br/>
              </p>
            <h3>Development</h3>
              <p>
                <a class="plain" href="/bugs/">Reporting Bugs</a><br/>
                <a class="plain" href="/bugs/known/">Known Bugs</a><br/>
                <a class="plain" href="/beta/">Beta Versions</a><br/>
              </p>
            <h3>Get in touch</h3>
              <p>
                <a class="plain" href="/contact/">Contact</a><br/>
              </p>
            <h3>Search</h3>
              <p>
<!-- Google CSE Search Box Begins  -->
<form action="http://www.google.com/cse" id="searchbox_014818976460624594421:r4x8-w4_mwu">
  <input type="hidden" name="cx" value="014818976460624594421:r4x8-w4_mwu" />
  <input type="text" name="q" id="searchbox" />
</form>
<script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=searchbox_014818976460624594421%3Ar4x8-w4_mwu&lang=en"></script>
<!-- Google CSE Search Box Ends -->
              </p>

            <div class="copyright">&copy; Copyright 2003-2011 Grml Live Linux</div>
            <p>&nbsp;</p>

      </div>
